[controller]
slurm-ctrl ansible_host=10.0.0.10 ansible_user=ubuntu

[compute_gpu]
slurm-gpu01 ansible_host=10.0.0.11 ansible_user=ubuntu gpu_count=1 slurm_cpus=32 real_memory_mb=250000
slurm-gpu02 ansible_host=10.0.0.12 ansible_user=ubuntu gpu_count=1 slurm_cpus=32 real_memory_mb=250000

[compute_cpu]
# slurm-cpu01 ansible_host=10.0.0.13 ansible_user=ubuntu gpu_count=0 slurm_cpus=32 real_memory_mb=250000

[compute:children]
compute_gpu
compute_cpu

[all:vars]
ansible_python_interpreter=/usr/bin/python3

